### PR TITLE
Attempt #1

### PR DESCRIPTION
**Pull request by randyvergil**

### CODE REVIEW

**Comment by limzcode** [comment]
sato1

**Comment by limzcode** [comment]
The error message "' ) ' expected" typically indicates that there is a missing closing parenthesis ')' somewhere in your code. In your provided code, it appears that the issue is related to the searchSong method call:

java
Copy code
searchSong(songTitleKeyword: "Lament");
In Java, when you call a method, you should use parentheses to enclose the method arguments. Therefore, you should modify this line to:

java
Copy code
searchSong("Lament");
This change ensures that you're passing the "Lament" string as an argument to the searchSong method correctly. Make similar adjustments if there are any other method calls with missing or incorrect parentheses.

**Comment by limzcode** [comment]
cannot

**Comment by limzcode** [comment]
The error you are encountering, "cannot find method," typically occurs when the method or function you are trying to call is not defined or imported in your code correctly. In your case, it seems like there might be an issue with method calls or imports in your Selenium WebDriver setup.

Here are some steps to troubleshoot and resolve the issue:

Make sure you have the required dependencies in your project. You are using WebDriverManager, TestNG, and Selenium WebDriver. Ensure that you have added these dependencies to your project's build configuration (e.g., using Maven or Gradle).

Check your import statements. Ensure that you have imported all necessary classes and packages. In your BaseTest class, you are using WebDriverManager and ChromeOptions. Make sure you have the appropriate import statements for these classes.

Review your method calls. Ensure that the methods you are trying to call exist and are defined correctly. Check for any typos or incorrect method signatures.

Verify that your test methods are correctly annotated with @Test from TestNG.

It appears that you are creating a new WebDriver instance in your LoginTests class. Since you already have a setup method (setupClass()) in your BaseTest class, you should use the WebDriver instance created there instead of creating a new one. This is essential for reusing the same WebDriver session across multiple test classes.

Here's an updated version of your LoginTests class:

java
Copy code
import org.testng.annotations.Test;

public class LoginTests extends BaseTest {

    @Test
    public void LoginEmptyEmailPasswordTest() {
        // The WebDriver instance should be obtained from the BaseTest class
        WebDriver driver = getDriver();

        String url = "https://qa.koel.app/";
        driver.get(url);
        Assert.assertEquals(driver.getCurrentUrl(), url);
    }
}
By using the getDriver() method from your BaseTest class, you can access the same WebDriver instance initialized in the setupClass() method of BaseTest. This ensures consistency across your test classes and prevents conflicts caused by creating multiple WebDriver instances.

**Comment by randyvergil** [comment]
Hi greetings I changed the setings but when I running the test I always get the same error message: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
________________________________

**Comment by randyvergil** [comment]
I submit a new attempt called attempt#3

**Pull request closed without merging**
