### PR TITLE
New

### PR DESCRIPTION
**Pull request by randyvergil**

### CODE REVIEW

**Comment by Berichicko** [comment]
Please finish the homework!You got this problem, please correct it. 

image

HINT

` WebElement registrationLink = driver.findElement(By.cssSelector("[href='registration']"));`

`String registrationUrl = "https://qa.koel.app/registration";`

**Comment by randyvergil** [comment]
Ok thanks I will try to fix the code but is getting so many error I don’t know why

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Berichicko** [comment]
Hello

Please, re-submit homework for review in LMS

**Comment by randyvergil** [comment]
I submitted a new pull report called attempt #2

**Comment by Berichicko** [comment]
Hello,

I have checked your homework 16, and I wanted to let you know that you're doing great! Keep up the excellent work!
Best wishes from the HW team (Alex, [aliaksandr@testpro.io](mailto:aliaksandr@testpro.io))!

804deb64dc406a20a75da05d91a1a69e

image

**Pull request closed without merging**
